### ISSUE TITLE
duplicated css codes

### ISSUE THREAD

**Issue by Angham116** [ca-g7/MainLineTeam#33]
don't duplicate css codes 
 e.g :

```css
 .team .Sectiontitle {
   text-align: center;
}
.header__logo img {
   width: 100px;
   height: 100px;
   text-align: center;
}
```

 they contain the same thing ```text-align: center``` 

so you can make: 
```css .team .Sectiontitle , 
     .header__logo img {
       text-align: center
    }
``` 
 and the same thing for another codes :+1:
